# Generated by Django 4.2.4 on 2023-08-14 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Device',
            new_name='Dispositivos',
        ),
        migrations.AddField(
            model_name='casa',
            name='areaCuadrada',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casa',
            name='cantidadKwh',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casa',
            name='cantidadPagar',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.AddField(
            model_name='metas',
            name='casa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='core.casa'),
        ),
    ]
