# Generated by Django 4.2.4 on 2023-08-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_metas_rename_device_dispositivos_casa_areacuadrada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casa',
            name='cantidadKwh',
        ),
        migrations.RemoveField(
            model_name='casa',
            name='cantidadPagar',
        ),
        migrations.AddField(
            model_name='casa',
            name='valores_kwh',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='casa',
            name='valores_pagar',
            field=models.JSONField(default=list),
        ),
    ]
