# Generated by Django 4.2.4 on 2023-08-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_casa_cantidadkwh_remove_casa_cantidadpagar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivos',
            name='consumoWPerH',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='horasActivo',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
