# Generated by Django 4.2.4 on 2023-08-16 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_casa_areacuadrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='areaCuadrada',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Area cuadrada de la casa'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre de la casa'),
        ),
        migrations.AlterField(
            model_name='dispositivos',
            name='consumoWPerH',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Consumo en Watts por hora'),
        ),
        migrations.AlterField(
            model_name='dispositivos',
            name='horasActivo',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Horas activo por dia'),
        ),
        migrations.AlterField(
            model_name='dispositivos',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre del dispositivo'),
        ),
        migrations.AlterField(
            model_name='metas',
            name='description',
            field=models.TextField(verbose_name='Descripcion de la meta'),
        ),
    ]
