# Generated by Django 4.2.4 on 2023-08-16 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_casa_areacuadrada_alter_casa_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='areaCuadrada',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Area cuadrada de la casa'),
        ),
    ]
